server:
  port: 8200

spring:
  application:
    name: authservice
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/cred_db?serverTimezone=UTC
    username: root
    password: root
    hikari:
      maximum-pool-size: 5
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true



eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
token:
  access:
    default_time: 1800
  refresh:
    default_time: 86400