server:
  port: ${DISCOVERY_PORT:8761}
spring:
  security:
    user:
      name: ${DISCOVERY_USERNAME:discUser}
      password: ${DISCOVERY_PASSWORD:discPassword}
      roles: SYSTEM
  application:
    name: ${APP_NAME:discovery-service}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_USERNAME:discUser}:${DISCOVERY_PASSWORD:discPassword}@${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
    register-with-eureka: false
    fetch-registry: false
    
management:
  endpoints:
    web:
      exposure:
        include: '*'